type LogContext = Record<string, unknown>;

function normalizeContext(context?: LogContext) {
  if (!context || Object.keys(context).length === 0) return undefined;
  return Object.fromEntries(Object.entries(context).map(([key, value]) => [
    key,
    /token|secret|password|authorization|cookie|email|session|intent|user.?id|display.?name|message.?body|payload|details|hint/i.test(key)
      ? "[redacted]"
      : value !== null && typeof value === "object" ? "[omitted object]" : value
  ]));
}

function summarizeError(error: unknown) {
  if (!error || typeof error !== "object") return "Server operation failed";
  const source = error as Record<string, unknown>;
  const summary: LogContext = {};
  // Preserve diagnostic codes/types/statuses, never raw SQL/Stripe error text.
  for (const key of ["name", "type", "code", "status", "statusCode"]) {
    const value = source[key];
    if ((typeof value === "string" && /^[A-Za-z0-9_]{1,80}$/.test(value)) ||
        (typeof value === "number" && Number.isFinite(value))) summary[key] = value;
  }
  // These machine-readable failures are generated by our webhook, not user text.
  if (typeof source.message === "string" && /^(contribution_(lookup|confirmation|failure_update)_failed|message_persistence_failed)$/.test(source.message)) {
    summary.reason = source.message;
  }
  return Object.keys(summary).length ? summary : "Server operation failed";
}

export function logServerInfo(scope: string, message: string, context?: LogContext) {
  console.info(`[${scope}] ${message}`, normalizeContext(context));
}

export function logServerWarn(scope: string, message: string, context?: LogContext) {
  console.warn(`[${scope}] ${message}`, normalizeContext(context));
}

export function logServerError(scope: string, message: string, error: unknown, context?: LogContext) {
  const payload = {
    ...(normalizeContext(context) ?? {}),
    error: summarizeError(error)
  };

  console.error(`[${scope}] ${message}`, payload);
}
